export type SceneItem = {
  id: string;
  title: string;
  description: string;
  duration: number;
  tags: string[];
  video: string;
  thumbnail: string;
  favorited?: boolean;
  active?: boolean;
};

export const SCENES: SceneItem[] = [
  {
    id: "scene-0",
    title: "Bless The Lord",
    description: "Sunlit wheat swaying in a warm, hazy afternoon breeze.",
    duration: 30,
    tags: ["Golden Hour", "Fields", "Warm"],
    video: "/videos/1-bless-lord.mp4",
    thumbnail: "/images/scenes/video-thumbs/1-bless-lord.jpg",
    favorited: true,
  },
  {
    id: "scene-1",
    title: "Motion Background",
    description: "A soft, motion-blurred horizon drifting between sea and sky.",
    duration: 45,
    tags: ["Abstract", "Horizon", "Motion Blur"],
    video: "/videos/2-motion-background.mp4",
    thumbnail: "/images/scenes/video-thumbs/2-motion-background.jpg",
    favorited: true,
  },
  {
    id: "scene-2",
    title: "Colored Galaxy",
    description: "A glowing nebula drifting through deep space, lit by distant stars.",
    duration: 60,
    tags: ["Space", "Nebula", "Stars"],
    video: "/videos/3-bright-colored.mp4",
    thumbnail: "/images/scenes/video-thumbs/3-bright-colored.jpg",
    favorited: true,
  },
  {
    id: "scene-3",
    title: "Trees and Fog",
    description: "Morning sun breaking through fog over a quiet pine forest.",
    duration: 30,
    tags: ["Forest", "Fog", "Sunrise"],
    video: "/videos/4-trees-fog.mp4",
    thumbnail: "/images/scenes/video-thumbs/4-trees-fog.jpg",
  },
  {
    id: "scene-4",
    title: "Triangle Clouds",
    description: "A soft low-poly gradient in warm pastel tones.",
    duration: 45,
    tags: ["Abstract", "Pastel", "Geometric"],
    video: "/videos/5-triangle-clouds.mp4",
    thumbnail: "/images/scenes/video-thumbs/5-triangle-clouds.jpg",
  },
  {
    id: "scene-5",
    title: "Blue Swirls",
    description: "Glowing blue and violet light strands drifting like tall grass.",
    duration: 60,
    tags: ["Abstract", "Light", "Purple"],
    video: "/videos/6-4k-blue.mp4",
    thumbnail: "/images/scenes/video-thumbs/6-4k-blue.jpg",
  },
  {
    id: "scene-6",
    title: "Flowing Water",
    description: "Dark water rippling gently under a dim, even light.",
    duration: 30,
    tags: ["Water", "Ripples", "Calm"],
    video: "/videos/7-flowing-water.mp4",
    thumbnail: "/images/scenes/video-thumbs/7-flowing-water.jpg",
  },
  {
    id: "scene-7",
    title: "Glimmering Forests",
    description: "Warm, out-of-focus light glimmering through evening woodland.",
    duration: 45,
    tags: ["Bokeh", "Warm", "Evening"],
    video: "/videos/8-glimmering.mp4",
    thumbnail: "/images/scenes/video-thumbs/8-glimmering.jpg",
  },
  {
    id: "scene-8",
    title: "Cubic Sparkles",
    description: "A kaleidoscope of vertical color bands pulsing around a bright core.",
    duration: 60,
    tags: ["Abstract", "Colorful", "Glitch"],
    video: "/videos/9-60fps-colorful.mp4",
    thumbnail: "/images/scenes/video-thumbs/9-60fps-colorful.jpg",
  },
  {
    id: "scene-9",
    title: "Effects Background",
    description: "Dense clouds lit from within by shifting orange, teal, and pink.",
    duration: 30,
    tags: ["Clouds", "Colorful", "Abstract"],
    video: "/videos/10-2015-effects.mp4",
    thumbnail: "/images/scenes/video-thumbs/10-2015-effects.jpg",
  },
  {
    id: "scene-10",
    title: "Effects Background 2",
    description: "A pastel sky of pink and lavender clouds drifting past.",
    duration: 45,
    tags: ["Sky", "Pastel", "Dreamy"],
    video: "/videos/11-2015-effects.mp4",
    thumbnail: "/images/scenes/video-thumbs/11-2015-effects.jpg",
  },
  {
    id: "scene-11",
    title: "Light Pole Shine",
    description: "Bright prismatic light beams breaking through layered clouds.",
    duration: 60,
    tags: ["Light Rays", "Clouds", "Colorful"],
    video: "/videos/12-60fps-light.mp4",
    thumbnail: "/images/scenes/video-thumbs/12-60fps-light.jpg",
  },
  {
    id: "scene-12",
    title: "Cyan Rainbow",
    description: "A faint rainbow arcing across a pastel sky as petals drift by.",
    duration: 30,
    tags: ["Rainbow", "Pastel", "Dreamy"],
    video: "/videos/13-60fps-welcome.mp4",
    thumbnail: "/images/scenes/video-thumbs/13-60fps-welcome.jpg",
  },
  {
    id: "scene-13",
    title: "Rainbow Space",
    description: "Sunbeams cutting through vivid rainbow-colored clouds.",
    duration: 45,
    tags: ["Clouds", "Rainbow", "Colorful"],
    video: "/videos/14-rainbow-animated.mp4",
    thumbnail: "/images/scenes/video-thumbs/14-rainbow-animated.jpg",
  },
  {
    id: "scene-14",
    title: "Mountains Loop",
    description: "Sunset flares over snow-dusted peaks and a quiet pine ridge.",
    duration: 60,
    tags: ["Mountains", "Snow", "Sunset"],
    video: "/videos/15-mountains.mp4",
    thumbnail: "/images/scenes/video-thumbs/15-mountains.jpg",
  },
  {
    id: "scene-15",
    title: "Summer Leaves",
    description: "Sprawling old trees on a green lawn as leaves drift down at dusk.",
    duration: 30,
    tags: ["Trees", "Golden Hour", "Falling Leaves"],
    video: "/videos/16-summer-leaves.mp4",
    thumbnail: "/images/scenes/video-thumbs/16-summer-leaves.jpg",
  },
  {
    id: "scene-16",
    title: "Night Sky",
    description: "A dense field of stars over the silhouette of distant mountains.",
    duration: 45,
    tags: ["Night", "Stars", "Mountains"],
    video: "/videos/17-night-sky.mp4",
    thumbnail: "/images/scenes/video-thumbs/17-night-sky.jpg",
  },
  {
    id: "scene-17",
    title: "Iceland Aurora",
    description: "Green aurora curtains rippling above a still northern lake.",
    duration: 60,
    tags: ["Aurora", "Night", "Lake"],
    video: "/videos/18-iceland-aurora.mp4",
    thumbnail: "/images/scenes/video-thumbs/18-iceland-aurora.jpg",
  },
  {
    id: "scene-18",
    title: "Light Column Particles",
    description: "A shaft of light falling through drifting dust and particles.",
    duration: 30,
    tags: ["Particles", "Abstract", "Glow"],
    video: "/videos/19-light-column.mp4",
    thumbnail: "/images/scenes/video-thumbs/19-light-column.jpg",
  },
  {
    id: "scene-19",
    title: "Looping Cloud",
    description: "Golden clouds rolling past as if seen from above at sunset.",
    duration: 45,
    tags: ["Clouds", "Golden Hour", "Aerial"],
    video: "/videos/20-looping-cloud.mp4",
    thumbnail: "/images/scenes/video-thumbs/20-looping-cloud.jpg",
  },
  {
    id: "scene-20",
    title: "Spring Clouds",
    description: "Soft pastel clouds catching low, diagonal light.",
    duration: 60,
    tags: ["Clouds", "Pastel", "Dreamy"],
    video: "/videos/21-spring-clouds.mp4",
    thumbnail: "/images/scenes/video-thumbs/21-spring-clouds.jpg",
  },
  {
    id: "scene-21",
    title: "Autumn Dream",
    description: "A quiet forest path buried in fallen red and orange leaves.",
    duration: 30,
    tags: ["Autumn", "Forest", "Path"],
    video: "/videos/22-autumn-dream.mp4",
    thumbnail: "/images/scenes/video-thumbs/22-autumn-dream.jpg",
  },
  {
    id: "scene-22",
    title: "Fall Background",
    description: "A tree-lined avenue glowing yellow with autumn leaves underfoot.",
    duration: 45,
    tags: ["Autumn", "Trees", "Park"],
    video: "/videos/23-fall.mp4",
    thumbnail: "/images/scenes/video-thumbs/23-fall.jpg",
  },
  {
    id: "scene-23",
    title: "Fresh Water",
    description: "Cool water foaming and splashing in close-up detail.",
    duration: 60,
    tags: ["Water", "Splash", "Cool Tones"],
    video: "/videos/24-fresh-water.mp4",
    thumbnail: "/images/scenes/video-thumbs/24-fresh-water.jpg",
  },
  {
    id: "scene-24",
    title: "Slow Splashing Water",
    description: "Droplets splashing slowly across dark blue water at night.",
    duration: 30,
    tags: ["Water", "Splash", "Night"],
    video: "/videos/25-slow-splashing.mp4",
    thumbnail: "/images/scenes/video-thumbs/25-slow-splashing.jpg",
  },
  {
    id: "scene-25",
    title: "Mist Clouds Night",
    description: "A hazy moon glowing behind slow-moving night clouds.",
    duration: 45,
    tags: ["Night", "Clouds", "Moonlight"],
    video: "/videos/26-strange-night.mp4",
    thumbnail: "/images/scenes/video-thumbs/26-strange-night.jpg",
  },
  {
    id: "scene-26",
    title: "Sunset Mountains",
    description: "The sun sinking behind misty mountains over open water.",
    duration: 60,
    tags: ["Sunset", "Mountains", "Water"],
    video: "/videos/27-sunset-mountains.mp4",
    thumbnail: "/images/scenes/video-thumbs/27-sunset-mountains.jpg",
  },
  {
    id: "scene-27",
    title: "Cold Night",
    description: "Soft, unfocused city lights glowing cyan through a night window.",
    duration: 30,
    tags: ["City", "Bokeh", "Night"],
    video: "/videos/31-cold-night.mp4",
    thumbnail: "/images/scenes/video-thumbs/31-cold-night.jpg",
  },
  {
    id: "scene-28",
    title: "Water Caustics",
    description: "Bright turquoise light rippling in underwater caustic patterns.",
    duration: 45,
    tags: ["Water", "Underwater", "Turquoise"],
    video: "/videos/32-water-caustics.mp4",
    thumbnail: "/images/scenes/video-thumbs/32-water-caustics.jpg",
  },
  {
    id: "scene-29",
    title: "Golden Rain",
    description: "A fern-lined stream catching golden light through the trees.",
    duration: 60,
    tags: ["Forest", "Stream", "Golden Hour"],
    video: "/videos/33-golden-rain.mp4",
    thumbnail: "/images/scenes/video-thumbs/33-golden-rain.jpg",
  },
  {
    id: "scene-30",
    title: "Explosive",
    description: "A billowing gold nebula cloud flaring against a field of stars.",
    duration: 30,
    tags: ["Space", "Nebula", "Stars"],
    video: "/videos/34-explosive.mp4",
    thumbnail: "/images/scenes/video-thumbs/34-explosive.jpg",
  },
  {
    id: "scene-31",
    title: "Galaxy",
    description: "A starry galaxy core with a bright comet-like streak of light.",
    duration: 45,
    tags: ["Space", "Galaxy", "Stars"],
    video: "/videos/35-galaxy.mp4",
    thumbnail: "/images/scenes/video-thumbs/35-galaxy.jpg",
  },
  {
    id: "scene-32",
    title: "Blue Sky Timelapse",
    description: "Simple white clouds drifting across a clear blue daytime sky.",
    duration: 60,
    tags: ["Sky", "Daytime", "Clouds"],
    video: "/videos/36-deep-blue.mp4",
    thumbnail: "/images/scenes/video-thumbs/36-deep-blue.jpg",
  },
];
