export type SceneItem = {
  id: string;
  title: string;
  description: string;
  duration: number;
  tags: string[];
  video: string;
  thumbnail: string;
  favorited?: boolean;
  active?: boolean;
};

export const SCENES: SceneItem[] = [
  {
    id: "scene-0",
    title: "Bless The Lord",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Ocean","Rain"],
    video: "/videos/1-bless-lord.mp4",
    thumbnail: "/cache/video-thumbs/1-bless-lord.avif",
    favorited: true,
  },
  {
    id: "scene-1",
    title: "Motion Background",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Focus","Deep"],
    video: "/videos/2-motion-background.mp4",
    thumbnail: "/cache/video-thumbs/2-motion-background.avif",
    favorited: true,
  },
  {
    id: "scene-2",
    title: "Colored Galaxy",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Nature","Morning"],
    video: "/videos/3-bright-colored.mp4",
    thumbnail: "/cache/video-thumbs/3-bright-colored.avif",
    favorited: true,
  },
  {
    id: "scene-3",
    title: "Trees and Fog",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Rain","Calm"],
    video: "/videos/4-trees-fog.mp4",
    thumbnail: "/cache/video-thumbs/4-trees-fog.avif",
  },
  {
    id: "scene-4",
    title: "Triangle Clouds",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Night","Ambient"],
    video: "/videos/5-triangle-clouds.mp4",
    thumbnail: "/cache/video-thumbs/5-triangle-clouds.avif",
  },
  {
    id: "scene-5",
    title: "Blue Swirls",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Fire","Focus"],
    video: "/videos/6-4k-blue.mp4",
    thumbnail: "/cache/video-thumbs/6-4k-blue.avif",
  },
  {
    id: "scene-6",
    title: "Flowing Water",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Train","Flow"],
    video: "/videos/7-flowing-water.mp4",
    thumbnail: "/cache/video-thumbs/7-flowing-water.avif",
  },
  {
    id: "scene-7",
    title: "Glimmering Forests",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Autumn","Woods"],
    video: "/videos/8-glimmering.mp4",
    thumbnail: "/cache/video-thumbs/8-glimmering.avif",
  },
  {
    id: "scene-8",
    title: "Cubic Sparkles",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Valley","Serene"],
    video: "/videos/9-60fps-colorful.mp4",
    thumbnail: "/cache/video-thumbs/9-60fps-colorful.avif",
  },
  {
    id: "scene-9",
    title: "Effects Background",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Ocean","Rain"],
    video: "/videos/10-2015-effects.mp4",
    thumbnail: "/cache/video-thumbs/10-2015-effects.avif",
  },
  {
    id: "scene-10",
    title: "Effects Background 2",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Focus","Deep"],
    video: "/videos/11-2015-effects.mp4",
    thumbnail: "/cache/video-thumbs/11-2015-effects.avif",
  },
  {
    id: "scene-11",
    title: "Light Pole Shine",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Nature","Morning"],
    video: "/videos/12-60fps-light.mp4",
    thumbnail: "/cache/video-thumbs/12-60fps-light.avif",
  },
  {
    id: "scene-12",
    title: "Cyan Rainbow",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Rain","Calm"],
    video: "/videos/13-60fps-welcome.mp4",
    thumbnail: "/cache/video-thumbs/13-60fps-welcome.avif",
  },
  {
    id: "scene-13",
    title: "Rainbow Space",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Night","Ambient"],
    video: "/videos/14-rainbow-animated.mp4",
    thumbnail: "/cache/video-thumbs/14-rainbow-animated.avif",
  },
  {
    id: "scene-14",
    title: "Mountains Loop",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Fire","Focus"],
    video: "/videos/15-mountains.mp4",
    thumbnail: "/cache/video-thumbs/15-mountains.avif",
  },
  {
    id: "scene-15",
    title: "Summer Leaves",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Train","Flow"],
    video: "/videos/16-summer-leaves.mp4",
    thumbnail: "/cache/video-thumbs/16-summer-leaves.avif",
  },
  {
    id: "scene-16",
    title: "Night Sky",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Autumn","Woods"],
    video: "/videos/17-night-sky.mp4",
    thumbnail: "/cache/video-thumbs/17-night-sky.avif",
  },
  {
    id: "scene-17",
    title: "Iceland Aurora",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Valley","Serene"],
    video: "/videos/18-iceland-aurora.mp4",
    thumbnail: "/cache/video-thumbs/18-iceland-aurora.avif",
  },
  {
    id: "scene-18",
    title: "Light Column Particles",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Ocean","Rain"],
    video: "/videos/19-light-column.mp4",
    thumbnail: "/cache/video-thumbs/19-light-column.avif",
  },
  {
    id: "scene-19",
    title: "Looping Cloud",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Focus","Deep"],
    video: "/videos/20-looping-cloud.mp4",
    thumbnail: "/cache/video-thumbs/20-looping-cloud.avif",
  },
  {
    id: "scene-20",
    title: "Spring Clouds",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Nature","Morning"],
    video: "/videos/21-spring-clouds.mp4",
    thumbnail: "/cache/video-thumbs/21-spring-clouds.avif",
  },
  {
    id: "scene-21",
    title: "Autumn Dream",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Rain","Calm"],
    video: "/videos/22-autumn-dream.mp4",
    thumbnail: "/cache/video-thumbs/22-autumn-dream.avif",
  },
  {
    id: "scene-22",
    title: "Fall Background",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Night","Ambient"],
    video: "/videos/23-fall.mp4",
    thumbnail: "/cache/video-thumbs/23-fall.avif",
  },
  {
    id: "scene-23",
    title: "Fresh Water",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Fire","Focus"],
    video: "/videos/24-fresh-water.mp4",
    thumbnail: "/cache/video-thumbs/24-fresh-water.avif",
  },
  {
    id: "scene-24",
    title: "Slow Splashing Water",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Train","Flow"],
    video: "/videos/25-slow-splashing.mp4",
    thumbnail: "/cache/video-thumbs/25-slow-splashing.avif",
  },
  {
    id: "scene-25",
    title: "Mist Clouds Night",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Autumn","Woods"],
    video: "/videos/26-strange-night.mp4",
    thumbnail: "/cache/video-thumbs/26-strange-night.avif",
  },
  {
    id: "scene-26",
    title: "Sunset Mountains",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Valley","Serene"],
    video: "/videos/27-sunset-mountains.mp4",
    thumbnail: "/cache/video-thumbs/27-sunset-mountains.avif",
  },
  {
    id: "scene-27",
    title: "Wedding Nature",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Ocean","Rain"],
    video: "/videos/28-wedding-download.mp4",
    thumbnail: "/cache/video-thumbs/28-wedding-download.avif",
  },
  {
    id: "scene-28",
    title: "Wedding Nature 2",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Focus","Deep"],
    video: "/videos/29-wedding-download.mp4",
    thumbnail: "/cache/video-thumbs/29-wedding-download.avif",
  },
  {
    id: "scene-29",
    title: "Wedding Nature 3",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Nature","Morning"],
    video: "/videos/30-wedding-download.mp4",
    thumbnail: "/cache/video-thumbs/30-wedding-download.avif",
  },
  {
    id: "scene-30",
    title: "Cold Night",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Rain","Calm"],
    video: "/videos/31-cold-night.mp4",
    thumbnail: "/cache/video-thumbs/31-cold-night.avif",
  },
  {
    id: "scene-31",
    title: "Water Caustics",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Night","Ambient"],
    video: "/videos/32-water-caustics.mp4",
    thumbnail: "/cache/video-thumbs/32-water-caustics.avif",
  },
  {
    id: "scene-32",
    title: "Golden Rain",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Fire","Focus"],
    video: "/videos/33-golden-rain.mp4",
    thumbnail: "/cache/video-thumbs/33-golden-rain.avif",
  },
  {
    id: "scene-33",
    title: "Explosive",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 30,
    tags: ["Train","Flow"],
    video: "/videos/34-explosive.mp4",
    thumbnail: "/cache/video-thumbs/34-explosive.avif",
  },
  {
    id: "scene-34",
    title: "Galaxy",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 45,
    tags: ["Autumn","Woods"],
    video: "/videos/35-galaxy.mp4",
    thumbnail: "/cache/video-thumbs/35-galaxy.avif",
  },
  {
    id: "scene-35",
    title: "Blue Sky Timelapse",
    description: "Immersive atmospheric experience for deep focus and relaxation.",
    duration: 60,
    tags: ["Valley","Serene"],
    video: "/videos/36-deep-blue.mp4",
    thumbnail: "/cache/video-thumbs/36-deep-blue.avif",
  },
];


